////////////////////////////////////////////////////////////////////////////////
// Warning: This file was automatically generated by SmallBufferGenerator.
//          If you edit this by hand, the next run of SmallBufferGenerator
//          will overwrite your edits.
////////////////////////////////////////////////////////////////////////////////

using System;
using System.Runtime.InteropServices;

using Unity.Burst;

namespace CommonEcs {
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct LinearHashMapBucket8<K, V> 
        where K : unmanaged, IEquatable<K> 
        where V : unmanaged {
        public ref struct Enumerator {
            private readonly LinearHashMapEntry<K, V>* m_Elements;

            private int m_Index;

            public Enumerator(LinearHashMapEntry<K, V>* elements) {
                this.m_Elements = elements;
                this.m_Index = -1;
            }

            public bool MoveNext() {
                // Note that we check for hasValue here so that slots with no value are skipped
                do {
                    ++this.m_Index;
                } while (!this.m_Elements[this.m_Index].hasValue && this.m_Index < Length);

                return this.m_Index < Length;
            }

            public ref LinearHashMapEntry<K, V> Current {
                get {
                    RequireIndexInBounds();

                    return ref this.m_Elements[this.m_Index];
                }
            }

            [BurstDiscard]
            public void RequireIndexInBounds() {
                if (this.m_Index < 0 || this.m_Index >= 8) {
                    // ReSharper disable once UseStringInterpolation (due to Burst)
                    throw new Exception(string.Format("Index out of bounds: {0}", this.m_Index));
                }
            }
        }

        private readonly LinearHashMapEntry<K, V> m_Element0;

        private readonly LinearHashMapEntry<K, V> m_Element1;

        private readonly LinearHashMapEntry<K, V> m_Element2;

        private readonly LinearHashMapEntry<K, V> m_Element3;

        private readonly LinearHashMapEntry<K, V> m_Element4;

        private readonly LinearHashMapEntry<K, V> m_Element5;

        private readonly LinearHashMapEntry<K, V> m_Element6;

        private readonly LinearHashMapEntry<K, V> m_Element7;

        public ref LinearHashMapEntry<K, V> this[int index] {
            get {
                RequireIndexInBounds(index);

                return ref GetElement(index);
            }
        }

        private ref LinearHashMapEntry<K, V> GetElement(int index) {
            fixed (LinearHashMapEntry<K, V>* elements = &this.m_Element0) {
                return ref elements[index];
            }
        }

        private void SetElement(int index, LinearHashMapEntry<K, V> value) {
            fixed (LinearHashMapEntry<K, V>* elements = &this.m_Element0) {
                elements[index] = value;
            }
        }

        public const int Length = 8;

        public Enumerator GetEnumerator() {
            // Safe because Enumerator is a 'ref struct'
            fixed (LinearHashMapEntry<K, V>* elements = &this.m_Element0) {
                return new Enumerator(elements);
            }
        }

        private static void RequireIndexInBounds(int index) {
            if (index < 0 || index >= 8) {
                // ReSharper disable once UseStringInterpolation (due to Burst)
                throw new Exception(string.Format("Index out of bounds: {0}", index));
            }
        }
    }
}