//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Common {
	/**
	 * A common interface for a class satisfying a condition on a certain type
	 */
	public interface ICondition<T> {

		/**
		 * Returns whether or not a certain condition is met on a certain instance
		 */
		bool IsMet(T instance);

	}
}
