//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using Common;

namespace Common {
	/**
	 * An entry in roulette selection
	 */
	public struct RouletteEntry<T> {
		private readonly T item;

		// roulette interval
		private float rouletteFrom;
		private float rouletteTo;

		public RouletteEntry(T item, float rouletteFrom, float rouletteTo) {
			this.item = item;
			this.rouletteFrom = rouletteFrom;
			this.rouletteTo = rouletteTo;
		}

		public T Item {
			get {
				return item;
			}
		}

		/**
		 * Returns whether or not the specified value is within its roulette
		 * interval.
		 */
		public bool IsWithinRoulette(float rouletteValue) {
			return this.rouletteFrom.TolerantLesserThanOrEquals(rouletteValue) && rouletteValue < this.rouletteTo;
		}

		public float RouletteFrom {
			get {
				return rouletteFrom;
			}
		}

        public float RouletteTo {
            get {
                return rouletteTo;
            }
        }

        public void SetRoulette(float from, float to) {
	        this.rouletteFrom = from;
	        this.rouletteTo = to;
        }
	}
}