//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using Common;

namespace Common {
	/**
	 * An entry in roulette selection
	 */
	public class RouletteEntry<T> {

		private T item;

		// roulette interval
		private float rouletteFrom;
		private float rouletteTo;

		/**
		 * Constructor
		 * We used an empty one so we could use it in a pool
		 */
		public RouletteEntry() {
		}

		public T Item {
			get {
				return item;
			}

			set {
				item = value;
			}
		}

		/**
		 * Sets the roulette values for evolution selection.
		 * 
		 * @param from
		 * @param to
		 */
		public void SetRoulette(float start, float end) {
			rouletteFrom = start;
			rouletteTo = end;
		}

		/**
		 * Returns whether or not the specified value is within its roulette
		 * interval.
		 */
		public bool IsWithinRoulette(float rouletteValue) {
			return Comparison.TolerantLesserThanOrEquals(this.rouletteFrom, rouletteValue) && rouletteValue < this.rouletteTo;
		}

		public float RouletteFrom {
			get {
				return rouletteFrom;
			}
		}

        public float RouletteTo {
            get {
                return rouletteTo;
            }

            set {
                this.rouletteTo = value;
            }
        }

    }
}

