//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Common.Signal {
	public interface ISignalParameters {
		/// <summary>
		/// Adds a parameter
		/// </summary>
		/// <param name="key"></param>
		/// <param name="value"></param>
		void AddParameter(string key, object value);

		/// <summary>
		/// Returns the parameter with the specified key
		/// Parameter may not exist. Client code should check.
		/// </summary>
		/// <param name="key"></param>
		/// <typeparam name="T"></typeparam>
		/// <returns></returns>
		Option<T> GetParameter<T>(string key) where T : class;

		/// <summary>
		/// Returns whether or not it has a parameter with the specified key
		/// </summary>
		/// <param name="key"></param>
		/// <returns></returns>
		bool HasParameter(string key);
	}
}
